// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwzc_ViYXtkkzzE7U-I9CbQ8xnhfn-bM',
    appId: '1:813148073098:web:ec8596e9fafa9dd2645173',
    messagingSenderId: '813148073098',
    projectId: 'aumet-db76e',
    authDomain: 'aumet-db76e.firebaseapp.com',
    storageBucket: 'aumet-db76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FQjLMH5tm-dqIfJ4wSD06y7kj4w3cfw',
    appId: '1:813148073098:android:1db6a906884e6f23645173',
    messagingSenderId: '813148073098',
    projectId: 'aumet-db76e',
    storageBucket: 'aumet-db76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsl6sZySLRvew7cK8-x19vGgy4b7qvfQ',
    appId: '1:813148073098:ios:7fe2f63017846775645173',
    messagingSenderId: '813148073098',
    projectId: 'aumet-db76e',
    storageBucket: 'aumet-db76e.appspot.com',
    iosClientId: '813148073098-2rq883mat8dud41g7qlpu0hjn59nfrb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsl6sZySLRvew7cK8-x19vGgy4b7qvfQ',
    appId: '1:813148073098:ios:7fe2f63017846775645173',
    messagingSenderId: '813148073098',
    projectId: 'aumet-db76e',
    storageBucket: 'aumet-db76e.appspot.com',
    iosClientId: '813148073098-2rq883mat8dud41g7qlpu0hjn59nfrb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBloc',
  );
}
